### PR TITLE
Add night color configuration location

### PR DESCRIPTION
**Pull request by cyqsimon**

### CODE REVIEW

**Comment by chxei** [comment]
Have you tested this on both Wayland and x11?

**Comment by chxei** [comment]
I'm positive that's the file on x11.

**Comment by chxei** [comment]
Thanks for your contribution @cyqsimon

**Comment by cyqsimon** [comment]
> Have you tested this on both Wayland and x11?

Just did, using a VM with Fedora KDE on Wayland. It also uses this file.

My main machine runs Endeavour OS KDE on Xorg FYI.

**Pull request merged**
